apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aicrme.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "aicrme.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ include "aicrme.authUsername" . | b64enc | quote }}
  password: {{ include "aicrme.authPassword" . | b64enc | quote }}
